services:
  - type: static_site
    name: newsreader
    env: static
    buildCommand: ''
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
